# Generated by Django 4.2.7 on 2023-11-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falloutRpg', '0016_alter_character_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='user',
            field=models.CharField(default='admin', max_length=64),
        ),
    ]
